---
- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - 1.1.1.1 - SCORED | PATCH | Ensure mounting of freevxfs filesystems is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install freevxfs"
    line: "install freevxfs /bin/true"
    state: present
    create: true
  when: debian_cis_rule_1_1_1_1|default(true)
  tags:
    - level1
    - scored
    - patch
    - freevxfs
    - filesystems
    - rule_1.1.1.1

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - 1.1.1.1 - SCORED | PATCH | Ensure Linux headers are present"
  package:
    name: "linux-headers-{{ ansible_kernel }}"
  when:
    - debian_cis_rule_1_1_1_1|default(true)
  ignore_errors: true
  tags:
    - level1
    - scored
    - patch
    - freevxfs
    - filesystems
    - rule_1.1.1.1

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - 1.1.1.1 - SCORED | PATCH | Remove freevxfs module"
  modprobe:
    name: freevxfs
    state: absent
  when:
    - debian_cis_rule_1_1_1_1|default(true)
  ignore_errors: true
  tags:
    - level1
    - scored
    - patch
    - freevxfs
    - filesystems
    - rule_1.1.1.1